global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'send_email'

receivers:
  - name: 'send_email'
    email_configs:
      - to: 'youremail@test.com'
        from: 'alertmanager@example.com'
        smarthost: 'smtp.gmail.com:587'  # SMTP server and port
        auth_username: 'mail@gmail.com'
        auth_password: 'yourpass'
        require_tls: true