# Use the official Amazon Linux 2 image as a base
FROM amazonlinux:2

# Set the working directory to /app
WORKDIR /app

# Update package list and install wget
RUN yum update -y && \
    yum install -y wget tar gzip && \
    yum clean all

# Download and install the node_exporter binary
RUN wget https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz && \
    tar xvfz node_exporter-1.2.2.linux-amd64.tar.gz && \
    mv node_exporter-1.2.2.linux-amd64/node_exporter /app/ && \
    rm -rf node_exporter-1.2.2.linux-amd64.tar.gz node_exporter-1.2.2.linux-amd64

# Expose the necessary port
EXPOSE 9100

# Run node_exporter when the container starts
CMD ["/app/node_exporter"]
