# Use the official Ubuntu 20.04 LTS as a base image
FROM ubuntu:20.04

# Set the working directory to /app
WORKDIR /app

# Download and install the node_exporter binary
RUN apt-get update && \
    apt-get install -y wget && \
    wget https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz && \
    tar xvfz node_exporter-1.2.2.linux-amd64.tar.gz && \
    mv node_exporter-1.2.2.linux-amd64/node_exporter /app/ && \
    rm -rf node_exporter-1.2.2.linux-amd64.tar.gz node_exporter-1.2.2.linux-amd64 && \
    apt-get remove -y wget && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Expose the necessary port
EXPOSE 9100

# Run node_exporter when the container starts
CMD ["/app/node_exporter"]
